serviceName: user_activity_service
port: 3000

database:
  host: localhost
  port: 5432
  dbname: teammates_data
  username: postgres
  password: Win

kafka:
  brokers:
    - broker-kafka:9094
  groupId: teammate-search
  maxMessageBytes: 33554432

topics:
  filterData: filter.data
  userPopularity: user.popularity

redis:
  host: localhost 
  port: 6379
  db: 0
  ttlSeconds: 600

