serviceName: teammate-search
port: 3000

database:
  host: teammate-db
  port: 5432
  dbname: teammates_data
  username: teammate_search
  password: teammate_search

kafka:
  brokers:
    - broker-kafka:9094
  groupId: teammate-search
  maxMessageBytes: 33554432

topics:
  filterData: filter.data
  userPopularity: user.popularity

redis:
  host: redis 
  port: 6379
  db: 0
  ttlSeconds: 600

